name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v2
      - name: Select Xcode version
        run: sudo xcode-select -s '/Applications/Xcode_14.0.app'
      - name: Show Xcode version
        run: xcodebuild -version
      - name: Build
        run: xcodebuild build -scheme SwipeableTabView -destination 'generic/platform=iOS'
      - name: Test
        run: xcodebuild test -scheme SwipeableTabView -destination 'platform=iOS Simulator,name=iPhone 14,OS=16.0'
