name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
      - name: Select Xcode version
        run: sudo xcode-select -s '/Applications/Xcode_13.2.1.app'
      - name: Show Xcode version
        run: xcodebuild -version
      - name: Build
        run: xcodebuild build -scheme SwipeableTabView -destination 'generic/platform=iOS'
